In [2]:
import pandas as pd

In [3]:
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [10]:
df.shape

(10000, 11)

In [12]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [25]:
df.groupby('fuel_type').model_year.agg(['count'])

           count
fuel_type
Diesel      2053
Gasoline    6913
Hybrid      1034

In [34]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [97]:
ef= df[df['origin'] =='Asia']

In [98]:
ef['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [103]:
a =df.groupby('origin')['fuel_efficiency_mpg'].max()

In [106]:
a

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [110]:
m = df.horsepower.mean()

In [181]:
m

np.float64(254.44601556505535)

In [172]:
frecv = df['horsepower'].value_counts().iloc[0]

In [173]:
frecv

np.int64(174)

In [174]:
df['horsepower'] = df['horsepower'].fillna(frecv)

In [175]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [176]:
df['horsepower'].value_counts()

horsepower
174.0    878
252.0    174
246.0    168
256.0    168
259.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [177]:
m1 = df.horsepower.mean()

In [178]:
m1

np.float64(247.3909)

In [180]:
m > m1

np.True_

In [5]:
df1 = df[df['origin'] == 'Asia']

In [6]:
X = df1[['vehicle_weight','model_year']].head(7).to_numpy()

In [7]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [10]:
X.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [12]:
XTX = X.T @ X

In [13]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [14]:
XTX_inv = np.linalg.inv(XTX)

In [15]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [19]:
Y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [20]:
Y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [23]:
 W = (XTX_inv @ X.T) @ Y

In [24]:
W

array([0.13644777, 0.2327492 ])

In [25]:
W.sum()

np.float64(0.36919696904925486)